# Generated by Django 2.2 on 2019-04-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(blank=True, max_length=120, null=True)),
                ('jobDescription', models.TextField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
