# Generated by Django 2.2 on 2019-04-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsmodel',
            name='jobsLink',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
